---
- name: remove installed ruby rpms
  yum: name={{ item }} state=absent
  with_items:
    - ruby
    - ruby-libs

- name: download ruby {{ ruby_ver }} archive
  get_url: url={{ ruby_archive }} dest={{ download_path }}/ruby-{{ ruby_ver }}.tar.gz

- name: extract ruby archive
  command: tar xzf ruby-{{ ruby_ver }}.tar.gz chdir={{ download_path }} creates={{ download_path }}/ruby-{{ ruby_ver }}

- name: configure ruby
  command: ./configure --prefix={{ install_prefix }} {{ configure_options }} chdir={{ download_path }}/ruby-{{ ruby_ver }} creates={{ install_prefix }}/bin/ruby

- name: make ruby
  command: make chdir={{ download_path }}/ruby-{{ ruby_ver }} creates={{ install_prefix }}/bin/ruby

- name: install ruby
  command: make install chdir={{ download_path }}/ruby-{{ ruby_ver }} creates={{ install_prefix }}/bin/ruby
